language: python
sudo: false
cache: pip
python:
  - "2.7"
env:
  - VCR_RECORD_MODE=none  # only use recorded tests, errors on nonexisting tests
  - VCR_RECORD_MODE=all   # don't use recorded tests, do it LIVE

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
before_install:
  - pip install codecov
install:
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install pytest pytest-pep8 pytest-flakes nose # we still need nose for the _eq functions for now
# command to run tests, e.g. python setup.py test
before_script: export PYTHONPATH=$PYTHONPATH:$(pwd)
script: py.test

after_success:
  - codecov
notifications:
  irc:
    channels:
      - "irc.nerv.fi#pyfibot"
    skip_join: true
